backend:
  name: git-gateway
  branch: master

media_folder: "src/img/uploads" # Media files will be stored in the repo under src/img/uploads
public_folder: "img/uploads"  # The src attribute for uploaded media will begin with img/uploads

collections:
  - name: "avaline" # Used in routes, e.g., /admin/collections/blog
    label: "Avalinės parduotuvės" # Used in the UI
    folder: "src/parduotuves/avaline" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Parduotuvės pavadinimas", name: "title", widget: "string"}
      - label: "Akcijos"
        name: "kokia_akcija"
        widget: "relation"
        collection: "akcijos"
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Šablonas", name: "layout", widget: "hidden", default: "parduotuve.pug"}
      - {label: "Parduotuvės kategorija", name: "tipas", widget: "hidden", default: "Avalinė"}
      - {label: "Kontaktinis telefonas", name: "tel", widget: "string"}
      - {label: "Kontaktinis el.pašto adresas", name: "mail", widget: "string"}
      - {label: "Darbo laikas", name: "darbo_laikas", widget: "string"}
      - {label: "Interneto adresas", name: "www", widget: "string"}
      - {label: "Vieta žemėlapyje", name: "map", widget: "string"}
      - {label: "Parduotuvės aprašymas", name: "body", widget: "markdown"}
  - name: "drabuziai" # Used in routes, e.g., /admin/collections/blog
    label: "Drabužių parduotuvės" # Used in the UI
    folder: "src/parduotuves/drabuziai" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Parduotuvės pavadinimas", name: "title", widget: "string"}
      - {label: "Šablonas", name: "layout", widget: "hidden", default: "parduotuve.pug"}
      - {label: "Parduotuvės kategorija", name: "tipas", widget: "hidden", default: "Drabužiai"}
      - {label: "Kontaktinis telefonas", name: "tel", widget: "string"}
      - {label: "Kontaktinis el.pašto adresas", name: "mail", widget: "string"}
      - {label: "Darbo laikas", name: "darbo_laikas", widget: "string"}
      - {label: "Interneto adresas", name: "www", widget: "string"}
      - {label: "Vieta žemėlapyje", name: "map", widget: "string"}
      - {label: "Parduotuvės aprašymas", name: "body", widget: "markdown"}
  - name: "aksesuarai-dovanos" # Used in routes, e.g., /admin/collections/blog
    label: "Aksesuarų ir dovanų parduotuvės" # Used in the UI
    folder: "src/parduotuves/aksesuarai-ir-dovanos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Parduotuvės pavadinimas", name: "title", widget: "string"}
      - {label: "Logotipas", name: "logo", widget: "image"}
      - {label: "Šablonas", name: "layout", widget: "hidden", default: "parduotuve.pug"}
      - {label: "Parduotuvės kategorija", name: "tipas", widget: "hidden", default: "Aksesuarai ir dovanos"}
      - {label: "Kontaktinis telefonas", name: "tel", widget: "string"}
      - {label: "Kontaktinis el.pašto adresas", name: "mail", widget: "string"}
      - {label: "Darbo laikas", name: "darbo_laikas", widget: "string"}
      - {label: "Interneto adresas", name: "www", widget: "string"}
      - {label: "Vieta žemėlapyje", name: "map", widget: "string"}
      - {label: "Parduotuvės aprašymas", name: "body", widget: "markdown"}
  - name: "renginys" # Used in routes, e.g., /admin/collections/blog
    label: "Renginiai" # Used in the UI
    folder: "src/renginys" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Aktyvus", name: "aktyvus", widget: "boolean"}
      - {label: "Pavadinimas", name: "title", widget: "string"}
      - {label: "Šablonas", name: "layout", widget: "hidden", default: "renginys.pug"}
      - {label: "Renginio data (nuo-iki)", name: "renginio_data", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Nuotrauka", name: "renginio_img", widget: "image"}
      - {label: "Aprašymas", name: "body", widget: "markdown"}
  - name: "akcijos" # Used in routes, e.g., /admin/collections/blog
    label: "Akcijos" # Used in the UI
    folder: "src/akcijos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Aktyvus", name: "aktyvus", widget: "boolean"}
      - {label: "Pavadinimas", name: "title", widget: "string"}
      - {label: "Šablonas", name: "layout", widget: "hidden", default: "renginys.pug"}
      - {label: "Akcijos pradžios data", name: "akcijos_pradzia", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Akcijos pabaigos data", name: "akcijos_pabaiga", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Nuotrauka", name: "renginio_img", widget: "image"}
      - {label: "Aprašymas", name: "body", widget: "markdown"}
      - label: "Kokia akcija"
        name: "kokia_akcija"
        widget: "list"
        fields:
          - {label: "Nuotraukos title", name: "nuotraukos_title", widget: "string"}
          - {label: "Nuotrauka", name: "nuotrauka", widget: "image"}